name: deploy to Docker hub

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/blog-streak:latest
      - name: Trigger Dockge
        env:
          WATCHTOWER_KEY: ${{ secrets.WATCHTOWER_KEY }}
        run: | 
          curl https://blog-trigger.sornchaithedev.com/v1/update \
          -H "Authorization: Bearer $WATCHTOWER_KEY"
